version: "3.9"
services:
  web:
    build: .
    container_name: erigea_web
    restart: unless-stopped
    ports:
      - "3000:3000"
  nginx:
    image: nginx:alpine
    container_name: erigea_nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    restart: unless-stopped

